import type { Skill, Project, Experience, Achievement, Certification, SocialLink, NavItem, Education } from "@/types";

export const navItems: NavItem[] = [
  { label: "Home", href: "#hero" },
  { label: "About", href: "#about" },
  { label: "Education", href: "#education" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Experience", href: "#experience" },
  { label: "Achievements", href: "#achievements" },
  { label: "Photography", href: "#photography" },
  { label: "Contact", href: "#contact" },
];

export const socialLinks: SocialLink[] = [
  {
    name: "GitHub",
    url: "https://github.com/Suryansh-54-tech",
    icon: "github",
    label: "View GitHub Profile",
  },
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/suryansh-singh54/",
    icon: "linkedin",
    label: "View LinkedIn Profile",
  },
  {
    name: "Instagram",
    url: "https://www.instagram.com/__suryansh__54?igsh=enJsMWhyZnZjOHJk",
    icon: "instagram",
    label: "View Instagram Profile",
  },
  {
    name: "LeetCode",
    url: "https://leetcode.com/u/9vxelmrGYL/",
    icon: "code",
    label: "View LeetCode Profile",
  },
  {
    name: "Email",
    url: "mailto:suryansh.18535@gmail.com",
    icon: "mail",
    label: "Send Email",
  },
];

export const skills: Skill[] = [
  // Programming Languages
  { name: "Java", icon: "code", level: 90, category: "frontend", color: "#ED8B00" },
  { name: "Python", icon: "code", level: 85, category: "frontend", color: "#3776AB" },
  { name: "JavaScript", icon: "code", level: 88, category: "frontend", color: "#F7DF1E" },
  { name: "TypeScript", icon: "code", level: 85, category: "frontend", color: "#3178C6" },
  { name: "HTML", icon: "code", level: 95, category: "frontend", color: "#E34F26" },
  { name: "CSS", icon: "code", level: 90, category: "frontend", color: "#1572B6" },
  // Frameworks
  { name: "React", icon: "code", level: 85, category: "frontend", color: "#61DAFB" },
  { name: "Next.js", icon: "code", level: 80, category: "frontend", color: "#000000" },
  { name: "Tailwind CSS", icon: "code", level: 90, category: "frontend", color: "#06B6D4" },
  { name: "Node.js", icon: "server", level: 80, category: "backend", color: "#339933" },
  { name: "Express.js", icon: "server", level: 75, category: "backend", color: "#000000" },
  // Database
  { name: "MySQL", icon: "database", level: 80, category: "backend", color: "#4479A1" },
  { name: "MongoDB", icon: "database", level: 75, category: "backend", color: "#47A248" },
  // Core Subjects
  { name: "Data Structures & Algorithms", icon: "code", level: 85, category: "tools", color: "#F59E0B" },
  { name: "DBMS", icon: "database", level: 80, category: "tools", color: "#3B82F6" },
  { name: "Operating Systems", icon: "server", level: 80, category: "tools", color: "#8B5CF6" },
  { name: "Computer Networks", icon: "globe", level: 80, category: "tools", color: "#06B6D4" },
  { name: "Cyber Security", icon: "shield", level: 85, category: "tools", color: "#EF4444" },
  // Cyber Security Tools
  { name: "Linux", icon: "terminal", level: 80, category: "tools", color: "#FCC624" },
  { name: "Windows Security", icon: "monitor", level: 75, category: "tools", color: "#0078D6" },
  { name: "Wireshark", icon: "activity", level: 70, category: "tools", color: "#1679A7" },
  { name: "Nmap", icon: "search", level: 70, category: "tools", color: "#000000" },
  { name: "OWASP Basics", icon: "shield-check", level: 75, category: "tools", color: "#10B981" },
  // Tools
  { name: "Git", icon: "git-branch", level: 90, category: "tools", color: "#F05032" },
  { name: "GitHub", icon: "github", level: 90, category: "tools", color: "#181717" },
  { name: "VS Code", icon: "code", level: 95, category: "tools", color: "#007ACC" },
  { name: "Postman", icon: "send", level: 85, category: "tools", color: "#FF6C37" },
];

export const projects: Project[] = [
  {
    id: "1",
    title: "Network Anomaly Detector",
    description: "Built a rule-based network anomaly detection system to analyze network traffic and identify suspicious behaviour using networking concepts and data visualization.",
    shortDescription: "Rule-based network anomaly detection with data visualization",
    image: "/projects/project1.png",
    tags: ["Python", "Networking", "Streamlit"],
    liveUrl: undefined,
    githubUrl: "TODO: Replace with real GitHub URL",
    featured: true,
    category: "web",
  },
  {
    id: "2",
    title: "ZeroFlux",
    description: "Interactive cyber security dashboard for Windows Event Viewer log visualization and security analysis.",
    shortDescription: "Windows Event Viewer log visualization dashboard",
    image: "/projects/project2.png",
    tags: ["Cyber Security", "Dashboard", "Windows"],
    liveUrl: undefined,
    githubUrl: "TODO: Replace with real GitHub URL",
    featured: true,
    category: "web",
  },
];

export const education: Education[] = [
  {
    id: "1",
    degree: "Bachelor of Technology (B.Tech)",
    specialization: "Computer Science Engineering (Cyber Security)",
    institution: "Pranveer Singh Institute of Technology (PSIT), Kanpur",
    university: "Dr. A.P.J. Abdul Kalam Technical University (AKTU)",
    period: "2023 – Present",
    percentage: "69.08% (Till 6th Semester)",
    location: "Kanpur, Uttar Pradesh, India",
    type: "bachelor",
  },
  {
    id: "2",
    degree: "Senior Secondary (Class XII)",
    institution: "Methodist High School, Kanpur",
    period: "2023",
    percentage: "60.7%",
    location: "Kanpur, Uttar Pradesh, India",
    type: "senior-secondary",
  },
  {
    id: "3",
    degree: "Secondary (Class X)",
    institution: "Methodist High School, Kanpur",
    period: "2021",
    percentage: "79.6%",
    location: "Kanpur, Uttar Pradesh, India",
    type: "secondary",
  },
];

export const experiences: Experience[] = [
  {
    id: "1",
    company: "Ingenious Club",
    role: "President",
    period: "2024 – Present",
    location: "Kanpur, Uttar Pradesh, India",
    description: [
      "Led and managed the Ingenious Club and coordinated student members.",
      "Planned and organized photography, technical, and cultural events.",
      "Supervised digital promotions and social media content for club activities.",
      "Coordinated with faculty and various student committees for successful event execution.",
      "Managed photography and media coverage during college events.",
      "Delegated responsibilities, mentored team members, and ensured smooth execution of club operations.",
      "Strengthened leadership, communication, team management, and event coordination skills.",
    ],
    technologies: ["Leadership", "Team Management", "Event Management", "Project Coordination", "Photography", "Content Creation", "Social Media Management", "Communication", "Problem Solving"],
    type: "full-time",
    current: true,
  },
  {
    id: "2",
    company: "Ingenious Club",
    role: "Senior Executive",
    period: "2024 – Present",
    location: "Kanpur, Uttar Pradesh, India",
    description: [
      "Designed and managed digital promotional content for club events.",
      "Assisted in organizing and executing technical and cultural events.",
      "Collaborated with cross-functional teams for event planning and coordination.",
      "Contributed to the club's digital branding and social media presence.",
      "Supported photography and media coverage during college events.",
      "Strengthened leadership, communication, teamwork, and organizational skills.",
    ],
    technologies: ["Leadership", "Teamwork", "Event Management", "Content Creation", "Digital Marketing", "Photography", "Canva", "Social Media", "Communication"],
    type: "full-time",
    current: true,
  },
  {
    id: "3",
    company: "Pranveer Singh Institute of Technology (PSIT), Kanpur",
    role: "Computer Science Undergraduate (Cyber Security)",
    period: "2023 – Present",
    location: "Kanpur, Uttar Pradesh, India",
    description: [
      "Learning software development, cybersecurity, networking and modern web technologies through coursework and personal projects.",
      "Specialized in Cyber Security with strong foundations in Java, Data Structures & Algorithms, DBMS, Operating Systems and Computer Networks.",
    ],
    technologies: ["Java", "Python", "JavaScript", "TypeScript", "React", "Next.js", "MySQL", "MongoDB", "Linux", "Wireshark", "Nmap"],
    type: "full-time",
    current: true,
  },
];

export const achievements: Achievement[] = [
  {
    id: "1",
    title: "Google Cloud Skills Boost Skill Badges",
    description: "Successfully completed multiple Google Cloud labs and Skill Badges, gaining hands-on experience with cloud infrastructure, AI, and Google Cloud services.",
    icon: "certificate",
    date: "2026",
    category: "certification",
  },
  {
    id: "2",
    title: "Coursera Professional Certifications",
    description: "Completed industry-recognized courses in programming, software development, cybersecurity, and emerging technologies through Coursera.",
    icon: "certificate",
    date: "2026",
    category: "certification",
  },
  {
    id: "3",
    title: "President – Ingenious Club, PSIT",
    description: "Led the college photography and creative club, managed student teams, coordinated campus events, and oversaw digital media initiatives while developing leadership and event management skills.",
    icon: "star",
    date: "2025",
    category: "recognition",
  },
  {
    id: "4",
    title: "Google Cloud Facilitator Program",
    description: "Selected as a participant in the Google Cloud Facilitator Program, completing hands-on cloud labs and strengthening practical cloud computing knowledge.",
    icon: "target",
    date: "2026",
    category: "milestone",
  },
];

export const certifications: Certification[] = [
  {
    id: "1",
    title: "Cybersecurity Threat Vectors and Mitigation",
    provider: "coursera",
    providerName: "Coursera",
    issuedBy: "Microsoft",
    issueDate: "May 28, 2026",
    credentialId: "FIU9IS14XADX",
    credentialUrl: "https://www.coursera.org/verify/FIU9IS14XADX",
    pdfUrl: "/certificates/Coursera FIU9IS14XADX.pdf",
    category: "security",
    description: "Comprehensive coverage of cybersecurity threat vectors, attack methodologies, and mitigation strategies. Includes hands-on labs for threat detection and incident response.",
  },
  {
    id: "2",
    title: "Introduction to Networking and Cloud Computing",
    provider: "coursera",
    providerName: "Coursera",
    issuedBy: "Microsoft",
    issueDate: "May 28, 2026",
    credentialId: "L9BV9ANLJMR9",
    credentialUrl: "https://www.coursera.org/verify/L9BV9ANLJMR9",
    pdfUrl: "/certificates/Coursera L9BV9ANLJMR9.pdf",
    category: "cloud",
    description: "Fundamentals of computer networking, cloud infrastructure, and distributed systems. Covers TCP/IP, DNS, cloud service models (IaaS, PaaS, SaaS), and Azure core services.",
  },
  {
    id: "3",
    title: "Introduction to Computers and Operating Systems and Security",
    provider: "coursera",
    providerName: "Coursera",
    issuedBy: "Microsoft",
    issueDate: "Aug 8, 2025",
    credentialId: "N1RAYEL0N847",
    credentialUrl: "https://www.coursera.org/verify/N1RAYEL0N847",
    pdfUrl: "/certificates/Coursera N1RAYEL0N847.pdf",
    category: "security",
    description: "Core concepts of computer architecture, operating systems (Windows/Linux), and foundational security principles. Includes process management, memory management, and access control.",
  },
  {
    id: "4",
    title: "Introduction to Game Design",
    provider: "coursera",
    providerName: "Coursera",
    issuedBy: "Epic Games",
    issueDate: "Jun 2, 2025",
    credentialId: "OKDALNSJ69YY",
    credentialUrl: "https://www.coursera.org/verify/OKDALNSJ69YY",
    pdfUrl: "/certificates/Coursera OKDALNSJ69YY.pdf",
    category: "programming",
    description: "Game design fundamentals including mechanics, dynamics, aesthetics, player psychology, and prototyping. Uses Unreal Engine concepts for practical application.",
  },
  {
    id: "5",
    title: "Cybercrime",
    provider: "coursera",
    providerName: "Coursera",
    issuedBy: "Royal Holloway, University of London",
    issueDate: "Aug 7, 2025",
    credentialId: "SF1R8FH2LQ87",
    credentialUrl: "https://www.coursera.org/verify/SF1R8FH2LQ87",
    pdfUrl: "/certificates/Coursera SF1R8FH2LQ87.pdf",
    category: "security",
    description: "In-depth analysis of cybercrime types, digital forensics, legal frameworks, and investigation techniques. Covers malware analysis, financial cybercrime, and international law enforcement cooperation.",
  },
];